[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-DFS-2016",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
