from typing import final

ENGINE: str

@final
class Position:
    def __init__(self, line: int, column: int, offset: int) -> None: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...
    @property
    def offset(self) -> int: ...

@final
class Span:
    def __init__(self, start: Position, end: Position) -> None: ...
    @property
    def start(self) -> Position: ...
    @property
    def end(self) -> Position: ...

@final
class Diagnostic:
    def __init__(
        self,
        code: str,
        message: str,
        path: str | None = None,
        span: Span | None = None,
        phase: str | None = None,
    ) -> None: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def path(self) -> str | None: ...
    @property
    def span(self) -> Span | None: ...
    @property
    def phase(self) -> str | None: ...

@final
class Event:
    def __init__(
        self,
        path: str,
        key: str,
        source_plane: str,
        datatype: str | None,
        value_type: str,
        structural_id: str | None,
        span: Span,
    ) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def source_plane(self) -> str: ...
    @property
    def datatype(self) -> str | None: ...
    @property
    def value_type(self) -> str: ...
    @property
    def structural_id(self) -> str | None: ...
    @property
    def span(self) -> Span: ...

@final
class CompileResult:
    def __init__(
        self,
        events: tuple[Event, ...],
        warnings: tuple[Diagnostic, ...],
        errors: tuple[Diagnostic, ...],
    ) -> None: ...
    @property
    def events(self) -> tuple[Event, ...]: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...
    @property
    def errors(self) -> tuple[Diagnostic, ...]: ...
    @property
    def ok(self) -> bool: ...
    def require_ok(self) -> CompileResult: ...

@final
class Value:
    @property
    def kind(self) -> str: ...
    @property
    def canonical(self) -> str | None: ...
    @property
    def decoded(self) -> object: ...

@final
class Clarifier:
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> str: ...

@final
class GenericArgument:
    @property
    def kind(self) -> str: ...
    @property
    def datatype(self) -> str | None: ...
    @property
    def value(self) -> str | None: ...
    @property
    def generics(self) -> tuple[GenericArgument, ...]: ...
    @property
    def clarifiers(self) -> tuple[Clarifier, ...]: ...

@final
class Capabilities:
    @property
    def source_bytes(self) -> str: ...
    @property
    def authored_lexemes(self) -> str: ...
    @property
    def origin(self) -> str: ...
    @property
    def span(self) -> str: ...
    @property
    def portable_extensions(self) -> str: ...
    @property
    def unknown_telex_fields(self) -> str: ...
    @property
    def event_order(self) -> str: ...
    @property
    def lineage(self) -> str: ...

@final
class Binding:
    @property
    def address(self) -> str: ...
    @property
    def full_address(self) -> str: ...
    @property
    def event_address(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def position(self) -> int | None: ...
    @property
    def source_plane(self) -> str | None: ...
    @property
    def representation_kind(self) -> str: ...
    @property
    def identity(self) -> str | None: ...
    @property
    def datatype(self) -> str | None: ...
    @property
    def generics(self) -> tuple[GenericArgument, ...]: ...
    @property
    def clarifiers(self) -> tuple[Clarifier, ...]: ...
    @property
    def value(self) -> Value: ...
    @property
    def origin(self) -> str | None: ...
    @property
    def span(self) -> str | None: ...
    @property
    def parent(self) -> Binding | None: ...
    @property
    def children(self) -> tuple[Binding, ...]: ...
    @property
    def attributes(self) -> Binding | None: ...
    @property
    def lineage(self) -> str: ...
    @property
    def event_ordinal(self) -> int | None: ...
    def member(self, name: str) -> Binding: ...
    def at_position(self, index: int) -> Binding: ...
    def __getitem__(self, key: str | int) -> Binding: ...
    def __len__(self) -> int: ...

@final
class Document:
    @property
    def source(self) -> str: ...
    @property
    def payload(self) -> Binding: ...
    @property
    def header(self) -> Binding: ...
    @property
    def full(self) -> Binding: ...
    @property
    def capabilities(self) -> Capabilities: ...
    def __getitem__(self, name: str) -> Binding: ...
    def at(self, address: str, scope: str = "payload") -> Binding: ...
    def by_identity(
        self, identity: str, scope: str = "payload"
    ) -> tuple[Binding, ...]: ...

def compile_json(source: str) -> bytes: ...
def compile_cts_json(
    source: str,
    mode: str | None = None,
    datatype_policy: str | None = None,
    rich: bool = False,
    limits_source: str | None = None,
    max_attribute_depth: int | None = None,
    max_separator_depth: int | None = None,
    max_generic_depth: int | None = None,
    max_events: int | None = None,
) -> bytes: ...
def compile_packed(
    source: str,
) -> tuple[
    list[tuple[object, ...]],
    list[tuple[object, ...]],
    list[tuple[object, ...]],
]: ...
def compile_native(source: str) -> CompileResult: ...
def compile_telex(source: str) -> tuple[bool, bytes]: ...
def compile_telex_profile(source: str) -> tuple[int, int, int, int, int, int]: ...
def pytonic_loads(
    source: str,
    datatype_policy: str | None = None,
    max_attribute_depth: int | None = None,
) -> Document: ...
